# Generated by Django 5.1 on 2025-01-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0002_slide_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ] 